services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=app_database'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
